version: 2.1
orbs:
  cicd: sedstart/cicd@dev:1
jobs:
  test-windows:
    machine:
      image: windows-server-2022-gui
    steps:
      - cicd/runlocal:    
          api_key: SEDSTART_API_KEY_PROD      
          project_id: 418
          test_id: 1937
          profile_id: 848
          browser: chrome
          headless: true
          environment: QA
workflows:
  test-workflow:
    jobs:
      - test
