version: 2.1

orbs:
  cicd: sedstart/cicd@dev:1

jobs:
  test-windows:
    executor:
      name: windows
      size: large
    steps:
      - cicd/runlocal:
          api_key: SEDSTART_API_KEY_PROD
          project_id: 418
          suite_id: 419
          profile_id: 848
          browser: chrome
          headless: true
          environment: QA

workflows:
  test-workflow:
    jobs:
      - test-windows
